# Generated by Django 3.2 on 2021-04-16 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0002_alter_post_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggest',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=100)),
                ('subject', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
